[project]
name = "ComfyUI-TKMemeCreator"
description = "Create A Meme"
version = "1.05"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/trashkollector/TKMemeCreator"

[tool.comfy]
PublisherId = "trashkollector"
DisplayName = "ComfyUI-TKMemeCreator"
Icon = ""

